#!/bin/bash
set -e

cd /usr/src/linux
srcdir=$(basename "$(readlink -f .)")
latest=$(make kernelrelease)
yes "" | make LSMOD="$HOME/.config/modprobed.db" localmodconfig LLVM=1 -j16
yes "" | make olddefconfig
make -j16
make modules_install -j16
make install -j16
dracut --force /boot/initramfs-"$latest".img --hostonly --kver "$latest"
cp -v /boot/vmlinuz /boot/vmlinuz-"$latest"

cd /usr/src
for d in linux-*; do
  if [[ "$d" != "$srcdir" ]]; then
    echo removing "$d"
    rm -rf "$d"
  fi
done
ln -snf "$srcdir" linux

cd /lib/modules
for m in *; do
  if [[ "$m" != "$latest" ]]; then
    echo removing modules "$m"
    rm -rf "$m"
  fi
done

cd /boot
for f in vmlinuz-* initramfs-* System.map-* config-*; do
  if [[ "$f" != *"$latest"* ]]; then
    echo removing boot file "$f"
    rm -f "$f"
  fi
done

echo regenerating grub config
grub-mkconfig -o /boot/grub/grub.cfg
echo ---done---

